### ISSUE TITLE
`permissions` is a useful way to modify the default permissions granted to the GITHUB_TOKEN.

### ISSUE THREAD

**Issue by monochromegane** [k1LoW/homebrew-tap#4]
Your approach to updating formulae using scheduler is very clever.
I've taken it on as a reference. Thank you.

When I try to the workflow in my repository, the permission setting is needed.
In some articles, they choose the “Read and write permissions” button in the “Workflow permissions” section under “Settings > Actions > General”.
However, we can use permissions to modify the default permissions granted to the GITHUB_TOKEN.
ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions

The permissions given to the GITHUB_TOKEN for the job should be minimal.
So, I can run your workflow by adding the settings:

```diff
jobs:
  update:
    runs-on: macos-latest
+     permissions:
+       contents: write
    steps:
```

ref: https://github.com/monochromegane/homebrew-tap/blob/main/.github/workflows/update.yaml

I hope this is helpful for you.
Thank you.

**Comment by k1LoW** [comment]
@monochromegane Thank you!
